insert into t_category (level, name) values (1, 'Women''s Clothing / Men''s Clothing / Underwear');
insert into t_category (level, name) values (1, 'Shoes & Boots / Bags & Luggage / Accessories');
insert into t_category (level, name) values (1, 'Children''s Clothing & Toys / Maternity & Baby / Supplies');
insert into t_category (level, name) values (1, 'Home Appliances / Digital Products / Mobile Phones');
insert into t_category (level, name) values (1, 'Cosmetics / Personal Care / Health Products');
insert into t_category (level, name) values (1, 'Jewelry / Glasses & Eyewear / Watches');
insert into t_category (level, name) values (1, 'Sports / Outdoor / Musical Instruments');
insert into t_category (level, name) values (1, 'Games / Anime / Movies & TV');
insert into t_category (level, name) values (1, 'Gourmet Food / Fresh Food / Snacks');
insert into t_category (level, name) values (1, 'Flowers / Pets / Agricultural Supplies');
insert into t_category (level, name) values (1, 'Fabric Procurement / Decoration / Building Materials');
insert into t_category (level, name) values (1, 'Furniture / Home Decor / Home Textiles');
insert into t_category (level, name) values (1, 'Cars / Used Cars / Car Supplies');
insert into t_category (level, name) values (1, 'Office Supplies / DIY / Hardware & Electronics');
insert into t_category (level, name) values (1, 'General Merchandise / Kitchenware / Home Healthcare');
insert into t_category (level, name) values (1, 'Learning / Gift Cards / Local Services');


insert into t_category (level, pid, name) values (2, 1, 'Women''s Clothing');
insert into t_category (level, pid, name) values (2, 1, 'Men''s Clothing');
insert into t_category (level, pid, name) values (2, 1, 'Underwear');
insert into t_category (level, pid, name) values (2, 2, 'Shoes & Boots');
insert into t_category (level, pid, name) values (2, 2, 'Bags & Luggage');
insert into t_category (level, pid, name) values (2, 2, 'Accessories');
insert into t_category (level, pid, name) values (2, 3, 'Children''s Clothing & Toys');
insert into t_category (level, pid, name) values (2, 3, 'Maternity');
insert into t_category (level, pid, name) values (2, 3, 'Supplies');
insert into t_category (level, pid, name) values (2, 4, 'Home Appliances');
insert into t_category (level, pid, name) values (2, 4, 'Digital Products');
insert into t_category (level, pid, name) values (2, 4, 'Mobile Phones');
insert into t_category (level, pid, name) values (2, 5, 'Cosmetics');
insert into t_category (level, pid, name) values (2, 5, 'Personal Care');
insert into t_category (level, pid, name) values (2, 5, 'Health Products');
insert into t_category (level, pid, name) values (2, 6, 'Jewelry');
insert into t_category (level, pid, name) values (2, 6, 'Glasses & Eyewear');
insert into t_category (level, pid, name) values (2, 6, 'Watches');
insert into t_category (level, pid, name) values (2, 7, 'Sports');
insert into t_category (level, pid, name) values (2, 7, 'Outdoor');
insert into t_category (level, pid, name) values (2, 7, 'Musical Instruments');
insert into t_category (level, pid, name) values (2, 8, 'Games');
insert into t_category (level, pid, name) values (2, 8, 'Anime');
insert into t_category (level, pid, name) values (2, 8, 'Movies & TV');
insert into t_category (level, pid, name) values (2, 9, 'Gourmet Food');
insert into t_category (level, pid, name) values (2, 9, 'Fresh Food');
insert into t_category (level, pid, name) values (2, 9, 'Snacks');
insert into t_category (level, pid, name) values (2, 10, 'Flowers');
insert into t_category (level, pid, name) values (2, 10, 'Pets');
insert into t_category (level, pid, name) values (2, 10, 'Agricultural Supplies');
insert into t_category (level, pid, name) values (2, 11, 'Fabric Procurement');
insert into t_category (level, pid, name) values (2, 11, 'Decoration');
insert into t_category (level, pid, name) values (2, 11, 'Building Materials');
insert into t_category (level, pid, name) values (2, 12, 'Furniture');
insert into t_category (level, pid, name) values (2, 12, 'Home Decor');
insert into t_category (level, pid, name) values (2, 12, 'Home Textiles');
insert into t_category (level, pid, name) values (2, 13, 'Cars');
insert into t_category (level, pid, name) values (2, 13, 'Used Cars');
insert into t_category (level, pid, name) values (2, 13, 'Car Supplies');
insert into t_category (level, pid, name) values (2, 14, 'Office Supplies');
insert into t_category (level, pid, name) values (2, 14, 'DIY');
insert into t_category (level, pid, name) values (2, 14, 'Hardware & Electronics');
insert into t_category (level, pid, name) values (2, 15, 'General Merchandise');
insert into t_category (level, pid, name) values (2, 15, 'Kitchenware');
insert into t_category (level, pid, name) values (2, 15, 'Home Healthcare');
insert into t_category (level, pid, name) values (2, 16, 'Learning');
insert into t_category (level, pid, name) values (2, 16, 'Gift Cards');
insert into t_category (level, pid, name) values (2, 16, 'Local Services');


insert into t_category (level, pid, name) values (3, 17, 'Dresses');
insert into t_category (level, pid, name) values (3, 17, 'Skirts');
insert into t_category (level, pid, name) values (3, 17, 'Knitwear');
insert into t_category (level, pid, name) values (3, 17, 'T-shirts');
insert into t_category (level, pid, name) values (3, 17, 'Short Jackets');
insert into t_category (level, pid, name) values (3, 17, 'Hoodies');
insert into t_category (level, pid, name) values (3, 17, 'Hanfu (Traditional Chinese Clothing)');
insert into t_category (level, pid, name) values (3, 17, 'JK Uniforms');
insert into t_category (level, pid, name) values (3, 17, 'Lolita Fashion');
insert into t_category (level, pid, name) values (3, 17, 'Shirts');
insert into t_category (level, pid, name) values (3, 17, 'Versatile Pants');
insert into t_category (level, pid, name) values (3, 17, 'Culottes');
insert into t_category (level, pid, name) values (3, 17, 'Jeans');
insert into t_category (level, pid, name) values (3, 17, 'Suits');
insert into t_category (level, pid, name) values (3, 17, 'Plus Size Women''s Clothing');
insert into t_category (level, pid, name) values (3, 17, 'Fashion Sets');
insert into t_category (level, pid, name) values (3, 17, 'Lace/Chiffon Blouses');
insert into t_category (level, pid, name) values (3, 17, 'Trench Coats');
insert into t_category (level, pid, name) values (3, 17, 'Casual Pants');
insert into t_category (level, pid, name) values (3, 17, 'Tank Tops & Camisoles');
insert into t_category (level, pid, name) values (3, 17, 'Vests');
insert into t_category (level, pid, name) values (3, 17, 'Denim Jackets');
insert into t_category (level, pid, name) values (3, 17, 'Wide-leg Pants');
insert into t_category (level, pid, name) values (3, 17, 'Middle-aged & Elderly Women''s Clothing');
insert into t_category (level, pid, name) values (3, 17, 'Wedding Dresses & Formal Wear');
insert into t_category (level, pid, name) values (3, 17, 'Ethnic Clothing');
insert into t_category (level, pid, name) values (3, 17, 'Leggings');
insert into t_category (level, pid, name) values (3, 17, 'Suit Pants');
insert into t_category (level, pid, name) values (3, 17, 'Tang Suits');
insert into t_category (level, pid, name) values (3, 17, 'Cheongsam/Qipao');


insert into t_category (level, pid, name) values (3, 18, 'Spring & Summer New Arrivals');
insert into t_category (level, pid, name) values (3, 18, 'T-shirts');
insert into t_category (level, pid, name) values (3, 18, 'Shirts');
insert into t_category (level, pid, name) values (3, 18, 'Polo Shirts');
insert into t_category (level, pid, name) values (3, 18, 'Casual Pants');
insert into t_category (level, pid, name) values (3, 18, 'Jeans');
insert into t_category (level, pid, name) values (3, 18, 'Suits & Sets');
insert into t_category (level, pid, name) values (3, 18, 'Jackets');
insert into t_category (level, pid, name) values (3, 18, 'Leather Jackets');
insert into t_category (level, pid, name) values (3, 18, 'Hoodies');
insert into t_category (level, pid, name) values (3, 18, 'Windbreakers');
insert into t_category (level, pid, name) values (3, 18, 'Business Suits');
insert into t_category (level, pid, name) values (3, 18, 'Denim Jackets');
insert into t_category (level, pid, name) values (3, 18, 'Baseball Jackets');
insert into t_category (level, pid, name) values (3, 18, 'Premium Quality Items');
insert into t_category (level, pid, name) values (3, 18, 'Leather Coats');
insert into t_category (level, pid, name) values (3, 18, 'Sweaters & Knitwear');
insert into t_category (level, pid, name) values (3, 18, 'Sports Pants');
insert into t_category (level, pid, name) values (3, 18, 'Work Pants');
insert into t_category (level, pid, name) values (3, 18, 'Cardigans');
insert into t_category (level, pid, name) values (3, 18, 'Vests');
insert into t_category (level, pid, name) values (3, 18, 'Wool Coats');
insert into t_category (level, pid, name) values (3, 18, 'Down Jackets');
insert into t_category (level, pid, name) values (3, 18, 'Cotton-padded Jackets');
insert into t_category (level, pid, name) values (3, 18, 'Middle-aged & Elderly Men''s Clothing');
insert into t_category (level, pid, name) values (3, 18, 'Couple Outfits');
insert into t_category (level, pid, name) values (3, 18, 'Plus Size Men''s Clothing');
insert into t_category (level, pid, name) values (3, 18, 'Ethnic Style');
insert into t_category (level, pid, name) values (3, 18, 'Department Store Brands');
insert into t_category (level, pid, name) values (3, 18, 'Celebrity & Influencer Brands');
insert into t_category (level, pid, name) values (3, 18, 'Original Designs');



insert into t_category (level, pid, name) values (3, 19, 'French Underwear');
insert into t_category (level, pid, name) values (3, 19, 'Wire-free Bras');
insert into t_category (level, pid, name) values (3, 19, 'Women''s Underwear');
insert into t_category (level, pid, name) values (3, 19, 'Bras');
insert into t_category (level, pid, name) values (3, 19, 'Men''s Underwear');
insert into t_category (level, pid, name) values (3, 19, 'Long-sleeve Pajamas');
insert into t_category (level, pid, name) values (3, 19, 'Nightgowns');
insert into t_category (level, pid, name) values (3, 19, 'Silk Pajamas');
insert into t_category (level, pid, name) values (3, 19, 'Stockings');
insert into t_category (level, pid, name) values (3, 19, 'Ankle Socks');
insert into t_category (level, pid, name) values (3, 19, 'Couple Pajamas');
insert into t_category (level, pid, name) values (3, 19, 'Strapless Bras');
insert into t_category (level, pid, name) values (3, 19, 'Tank Tops');
insert into t_category (level, pid, name) values (3, 19, 'Bathrobes');
insert into t_category (level, pid, name) values (3, 19, 'Men''s Pajamas');
insert into t_category (level, pid, name) values (3, 19, 'Shapewear');
insert into t_category (level, pid, name) values (3, 19, 'Underwear Sets');
insert into t_category (level, pid, name) values (3, 19, 'Leggings');
insert into t_category (level, pid, name) values (3, 19, 'Onesie Pajamas');
insert into t_category (level, pid, name) values (3, 19, 'Push-up Bras');
insert into t_category (level, pid, name) values (3, 19, 'Men''s Socks');
insert into t_category (level, pid, name) values (3, 19, 'Women''s Cotton Socks');
insert into t_category (level, pid, name) values (3, 19, 'Cartoon Pajamas');
insert into t_category (level, pid, name) values (3, 19, 'Seamless Underwear');
insert into t_category (level, pid, name) values (3, 19, 'Teen Bras');
insert into t_category (level, pid, name) values (3,28,'iphone')