"""创建 Product 表

Revision ID: 20260202154837
Revises: d8a93a43ec4d
Create Date: 2026-02-02 15:48:38

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20260202154837'
down_revision = 'd8a93a43ec4d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_product',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=512), nullable=False),
        sa.Column('price', sa.Float(), nullable=True, server_default='0'),
        sa.Column('number', sa.Integer(), nullable=True, server_default='0'),
        sa.Column('introduce', sa.Text(), nullable=True),
        sa.Column('big_img', sa.String(length=255), nullable=True),
        sa.Column('small_img', sa.String(length=255), nullable=True),
        sa.Column('state', sa.Integer(), nullable=True),
        sa.Column('is_promote', sa.Integer(), nullable=True),
        sa.Column('hot_number', sa.Integer(), nullable=True),
        sa.Column('weight', sa.Integer(), nullable=True),
        sa.Column('cid_one', sa.Integer(), nullable=True),
        sa.Column('cid_two', sa.Integer(), nullable=True),
        sa.Column('cid_three', sa.Integer(), nullable=True),
        sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['cid_one'], ['t_category.id'], ),
        sa.ForeignKeyConstraint(['cid_two'], ['t_category.id'], ),
        sa.ForeignKeyConstraint(['cid_three'], ['t_category.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_product')
    # ### end Alembic commands ###
