"""empty message

Revision ID: 47b2d4af2c43
Revises: a1206565e49c
Create Date: 2026-01-18 15:33:33.541123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b2d4af2c43'
down_revision = 'a1206565e49c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_roles_menus',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('menus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menus_id'], ['t_menus.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['t_role.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_roles_menus')
    # ### end Alembic commands ###
