"""empty message

Revision ID: a54a265bbb23
Revises: 47b2d4af2c43
Create Date: 2026-01-18 15:39:47.221012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a54a265bbb23'
down_revision = '47b2d4af2c43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_roles_menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('t_roles_menus_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 't_menus', ['menu_id'], ['id'])
        batch_op.drop_column('menus_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_roles_menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menus_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('t_roles_menus_ibfk_1'), 't_menus', ['menus_id'], ['id'])
        batch_op.drop_column('menu_id')

    # ### end Alembic commands ###
