from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fix_val_field'
down_revision = 'a54a265bbb23'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_attribute', 'val',
                   existing_type=mysql.VARCHAR(length=255),
                   type_=sa.JSON(),
                   existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_attribute', 'val',
                   existing_type=sa.JSON(),
                   type_=mysql.VARCHAR(length=255),
                   existing_nullable=True)