### add the attribute 
POST http://localhost:5000/attributes/
Content-Type: application/json


{
    "name":"color",
    "_type":"static",
    "val":"space black",
    "cid":82
}




###get the category attribution base on category id
GET http://localhost:5000/attributes/?cid=65&_type=dynamic


### get the category attribution base on the brand id 
GET http://localhost:5000/attribute/1/



### update the category attribute base on the attribution
PUT http://localhost:5000/attribute/23/ 
Content-Type: application/json

{
    "name":"color",
    "_type":"static",
    "val":"black",
    "cid":82
}



### delete the attibution base on the attrubution id
DELETE http://localhost:5000/attribute/23/